info:
  component: 'Spotippos API'
  build:
    version: '@project.version@'
    name: '@project.name@'

server:
  port: 8080

#Spring
spring:
  application:
    name: spotippos-api

files:
  provinces: provinces.json
  properties: properties.json

validation:
  beds:
    max: 5
    min: 1
  baths:
    max: 4
    min: 1
  squareMeters:
    max: 240
    min: 20
